import fs from 'fs';
import path from 'path';
import { parseStyleFile, isStyleFile } from './css-parser';

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'build', 'dist', '.next', '.nuxt',
  '.cache', 'coverage', '.turbo', '.output', 'out',
]);

export function writeDts(filePath: string, classNames: string[]): boolean {
  const lines = [
    '// This file is auto-generated by css-modules-lint',
    '// Do not edit manually',
    'declare const styles: {',
    ...classNames.map((name) => `  readonly ${JSON.stringify(name)}: string;`),
    '};',
    'export default styles;',
    '',
  ];

  const dtsPath = filePath + '.d.ts';
  const content = lines.join('\n');

  // Only write if changed to avoid unnecessary fs writes / watch triggers
  const existing = fs.existsSync(dtsPath) ? fs.readFileSync(dtsPath, 'utf-8') : null;
  if (existing !== content) {
    fs.writeFileSync(dtsPath, content);
    return true;
  }
  return false;
}

export function generateDts(filePath: string): boolean {
  const parsed = parseStyleFile(filePath);
  if (!parsed) return false;

  const classNames = [
    ...Object.keys(parsed.classes),
    ...Object.keys(parsed.exportProps),
  ];

  return writeDts(filePath, classNames);
}

export function findStyleFiles(dir: string): string[] {
  const results: string[] = [];

  function walk(d: string) {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry.name)) continue;
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (isStyleFile(full)) {
        results.push(full);
      }
    }
  }

  walk(dir);
  return results;
}

function watchStyleFiles(dir: string): fs.FSWatcher {
  const watcher = fs.watch(dir, { recursive: true }, (_eventType, filename) => {
    if (!filename) return;
    const full = path.resolve(dir, filename);
    if (!isStyleFile(full)) return;

    if (!fs.existsSync(full)) {
      // File deleted — remove .d.ts
      const dtsPath = full + '.d.ts';
      if (fs.existsSync(dtsPath)) {
        fs.unlinkSync(dtsPath);
        console.log(`Removed: ${filename}.d.ts`);
      }
      return;
    }

    if (generateDts(full)) {
      console.log(`Updated: ${filename}.d.ts`);
    }
  });

  process.on('SIGINT', () => { watcher.close(); process.exit(0); });
  process.on('SIGTERM', () => { watcher.close(); process.exit(0); });

  return watcher;
}

export function generate(args: string[]): void {
  const watchMode = args.includes('--watch');
  const srcDir = process.cwd();

  const styleFiles = findStyleFiles(srcDir);

  let generated = 0;
  for (const file of styleFiles) {
    if (generateDts(file)) generated++;
  }

  console.log(`Generated ${generated} .d.ts file${generated !== 1 ? 's' : ''} (${styleFiles.length} CSS modules found).`);

  if (watchMode) {
    console.log('Watching for changes...');
    watchStyleFiles(srcDir);
  }
}
